const PHOTOCOUNT = 25;
const COUNT_STEP = 5;
const MAX_HASHTAGS = 5;
const MAX_SYMBOLS = 20;
const MAX_COMMENT_LENGTH = 140;

export { PHOTOCOUNT, COUNT_STEP, MAX_HASHTAGS, MAX_SYMBOLS, MAX_COMMENT_LENGTH };
